server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://ep-cold-hall-15535769.eu-central-1.aws.neon.fl0.io:5432/smartpoke-api?sslmode=require
    username: fl0user
    password: zP8YMnE5eAtZ
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: smartpoke-api

#DATOS NECESARIOS PARA CONSUMIR LA API DE OPENFOODFACTS.ORG
openfoodfacts:
  product-url: "https://world.openfoodfacts.org/api/v2/product/%s?fields=%s"
  filter: "?fields=product_name,code,allergens_tags,allergens,traces_hierarchy,image_front_url,brands,id,product_name,ingredients_text,nutriments,countries,labels,nutrition_grades,categories,categories_tags,generic_name,image_front_small_url,ingredients_hierarchy,ingredients_tags,ingredients_original_tags,ingredients_text_es,quantity"
  supermarket-url: "https://api.openfoodfacts.org/api/v2/search?stores_tags=%s&fields=%s&page=%d"

recipeScraper:
  server-url: "http://localhost:5000/scrape"


#LISTA DE SUPERMERCADOS DE LOS QUE COJE LOS PRODUCTOS
supermarkets:
  - mercadona
  - carrefour